## Load packages and code

In [1]:
import numpy as np
import sys
sys.path.insert(0, '../src/')
from BiCM import *

# BiCM example code

In [20]:
adjacency_matrix = np.array([[]])
degree_sequence_in = np.array([1,2,1,1])
degree_sequence_out = np.array([2,2,1])
degree_sequence = list(np.concatenate([degree_sequence_in, degree_sequence_out]))
n_rows = len(degree_sequence_in)
n_cols = len(degree_sequence_out)

Set up the Binary CM problem

In [22]:
bicm = bicm_leastSquares(degree_sequence, n_rows, n_cols)

Solve the system using root solver

In [23]:
bicm.solve_root()

Generate the probability matrix from solved x and y values

In [24]:
bicm.generate_p_adjacency()

In [25]:
bicm.p_adjacency

array([[0.41368749, 0.41368749, 0.17262502],
       [0.75893754, 0.75893754, 0.48212493],
       [0.41368749, 0.41368749, 0.17262502],
       [0.41368749, 0.41368749, 0.17262502]])

# BiSCM example code

In [26]:
import BiSCM as biscm

In [27]:
dseq = np.concatenate([np.array([0,1,0,1,0]),np.array([1,1,1,1,2])])
dim = (3,2)
cost_vector = np.ones(10)
tot_dim = 5 #number of nodes (rows + cols)
rows = 3 # nodes on one layer
cols = 2 # nodes on the other
max_bb = 2 #max rating

In [31]:
x0_init_guess = np.ones(len(dseq)) * 1

In [32]:
l_equations = lambda x: biscm.equations(x, dseq, max_bb, rows, tot_dim, cost_vector)
l_jac = lambda x: biscm.jacobian(x, dseq, max_bb, rows, tot_dim, cost_vector)
sol = opt.least_squares(fun = l_equations, x0 = x0_init_guess, jac = l_jac, tr_solver = 'lsmr', xtol = 1e-12, max_nfev = 1000, verbose = 2)

probs = biscm.get_matrix(sol.x, rows, tot_dim, max_bb)

   Iteration     Total nfev        Cost      Cost reduction    Step norm     Optimality   
       0              1         0.0000e+00                                    0.00e+00    
`gtol` termination condition is satisfied.
Function evaluations 1, initial cost 0.0000e+00, final cost 0.0000e+00, first-order optimality 0.00e+00.


In [33]:
probs

array([[0.33333333, 0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333, 0.33333333]])

In [34]:
cost_vector

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])